// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQRlQ0nXFx76pK9iVU4pHeyL5S3R4m2FI',
    appId: '1:982637508834:web:6b393c0920aaa1d8b986bb',
    messagingSenderId: '982637508834',
    projectId: 'medical-rekam',
    authDomain: 'medical-rekam.firebaseapp.com',
    storageBucket: 'medical-rekam.appspot.com',
    measurementId: 'G-9SCWJ0D9LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKYmQVEbUa5ELnwiFojj795WkHznqKqH4',
    appId: '1:982637508834:android:761bceb94b85b1b3b986bb',
    messagingSenderId: '982637508834',
    projectId: 'medical-rekam',
    storageBucket: 'medical-rekam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWO-IdolW350xYl4BU6obCl389Vnzh3E',
    appId: '1:982637508834:ios:b318483203eb6f0fb986bb',
    messagingSenderId: '982637508834',
    projectId: 'medical-rekam',
    storageBucket: 'medical-rekam.appspot.com',
    iosBundleId: 'com.example.projectrekammedis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWO-IdolW350xYl4BU6obCl389Vnzh3E',
    appId: '1:982637508834:ios:b318483203eb6f0fb986bb',
    messagingSenderId: '982637508834',
    projectId: 'medical-rekam',
    storageBucket: 'medical-rekam.appspot.com',
    iosBundleId: 'com.example.projectrekammedis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQRlQ0nXFx76pK9iVU4pHeyL5S3R4m2FI',
    appId: '1:982637508834:web:e5f5d0bc9089fd51b986bb',
    messagingSenderId: '982637508834',
    projectId: 'medical-rekam',
    authDomain: 'medical-rekam.firebaseapp.com',
    storageBucket: 'medical-rekam.appspot.com',
    measurementId: 'G-Z1GB8SXMGJ',
  );
}
